-- ============================================================
-- 新生命教会 · 关怀探访系统（网页版）数据库结构
-- 在 Supabase → SQL Editor 里整段粘贴运行即可
-- ============================================================

-- ---------- 枚举类型 ----------
do $$ begin
  create type user_role      as enum ('admin','leader','volunteer');           -- 管理员/负责人/同工
  create type visitor_status as enum ('待分配','跟进中','已联系','已安排小组','福音群','失联');
  create type identity_type  as enum ('基督徒','慕道友','未知');
  create type contact_result as enum ('已联系','未接','联系不上');
exception when duplicate_object then null; end $$;

-- ---------- 用户档案（与 auth.users 一对一，兼作「同工」名单）----------
create table if not exists profiles (
  id         uuid primary key references auth.users on delete cascade,
  name       text,
  email      text,
  role       user_role not null default 'volunteer',
  area       text,                          -- 负责区域（可选）
  active     boolean default true,
  created_at timestamptz default now()
);

-- ---------- 小组 ----------
create table if not exists groups (
  id           bigint generated by default as identity primary key,
  name         text not null,
  cover_area   text,           -- 覆盖区域（用于就近匹配）
  leader_name  text,
  leader_email text,
  meet_time    text
);

-- ---------- 访客（主数据）----------
create table if not exists visitors (
  id               bigint generated by default as identity primary key,
  name             text not null,
  phone            text,
  email            text,
  area             text,
  identity         identity_type  default '未知',
  first_visit      date default current_date,
  visit_count      int  default 1,
  status           visitor_status default '待分配',
  assignee_id      uuid references profiles(id),
  assign_date      timestamptz,
  last_result      contact_result,
  last_contact_date timestamptz,
  escalated        boolean default false,
  note             text,
  created_at       timestamptz default now(),
  created_by       uuid references profiles(id)
);

-- ---------- 跟进记录 ----------
create table if not exists followups (
  id         bigint generated by default as identity primary key,
  visitor_id bigint references visitors(id) on delete cascade,
  by_id      uuid references profiles(id),
  by_name    text,
  result     contact_result,
  encouraged boolean,
  note       text,
  created_at timestamptz default now()
);

-- ---------- 设置（键值）----------
create table if not exists config (
  key   text primary key,
  value text
);
insert into config(key,value) values
  ('教会名称','新生命国语播道会'),
  ('来访达标次数','4'),
  ('失联周数','4')
on conflict (key) do nothing;

-- ============================================================
-- 角色判断辅助函数（SECURITY DEFINER 避免 RLS 递归）
-- ============================================================
create or replace function has_role(check_roles user_role[])
returns boolean language sql security definer stable as $$
  select exists(select 1 from profiles where id = auth.uid() and role = any(check_roles));
$$;

-- 新用户注册时自动建档（默认角色 volunteer）
create or replace function handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into profiles(id, email, name, role)
  values (new.id, new.email,
          coalesce(new.raw_user_meta_data->>'name', split_part(new.email,'@',1)),
          'volunteer')
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ============================================================
-- 行级安全（RLS）—— 权限的核心
-- ============================================================
alter table profiles  enable row level security;
alter table visitors  enable row level security;
alter table followups enable row level security;
alter table groups    enable row level security;
alter table config    enable row level security;

-- profiles：本人可读自己；负责人/管理员可读全部；管理员可改
drop policy if exists p_profiles_select on profiles;
create policy p_profiles_select on profiles for select using (
  id = auth.uid() or has_role(array['leader','admin']::user_role[])
);
drop policy if exists p_profiles_self_update on profiles;
create policy p_profiles_self_update on profiles for update using (id = auth.uid());
drop policy if exists p_profiles_admin_all on profiles;
create policy p_profiles_admin_all on profiles for all using (has_role(array['admin']::user_role[]));

-- visitors：同工只能看/改分配给自己的；负责人/管理员看/改全部
drop policy if exists v_select on visitors;
create policy v_select on visitors for select using (
  has_role(array['leader','admin']::user_role[]) or assignee_id = auth.uid()
);
drop policy if exists v_insert on visitors;
create policy v_insert on visitors for insert with check (
  has_role(array['leader','admin']::user_role[])
);
drop policy if exists v_update_leader on visitors;
create policy v_update_leader on visitors for update using (
  has_role(array['leader','admin']::user_role[])
);
drop policy if exists v_update_assignee on visitors;
create policy v_update_assignee on visitors for update using (assignee_id = auth.uid());
drop policy if exists v_delete on visitors;
create policy v_delete on visitors for delete using (has_role(array['admin']::user_role[]));

-- followups：负责人/管理员看全部；同工看自己分配访客的记录；任何登录者可插入自己的记录
drop policy if exists f_select on followups;
create policy f_select on followups for select using (
  has_role(array['leader','admin']::user_role[])
  or exists(select 1 from visitors x where x.id = visitor_id and x.assignee_id = auth.uid())
);
drop policy if exists f_insert on followups;
create policy f_insert on followups for insert with check (by_id = auth.uid());

-- groups / config：登录者可读；管理员可改
drop policy if exists g_select on groups;
create policy g_select on groups for select using (auth.role() = 'authenticated');
drop policy if exists g_admin on groups;
create policy g_admin on groups for all using (has_role(array['admin']::user_role[]));

drop policy if exists c_select on config;
create policy c_select on config for select using (auth.role() = 'authenticated');
drop policy if exists c_admin on config;
create policy c_admin on config for all using (has_role(array['admin']::user_role[]));

-- ============================================================
-- 提示：注册第一个账号后，用下面这行把自己设为管理员
--   update profiles set role='admin' where email='你的邮箱';
-- ============================================================
